/soc/oplus,pps_charge/silicon_p_770/oplus,pps_strategy_batt_high_temp 0x1c2 0x1d6 0x1ea 0x1c2 0x1d6 0x1ea
/soc/oplus,pps_charge/silicon_p_770/oplus,pps_strategy_high_current 0x1676 0xfa0 0x9c4 0x1676 0xfa0 0x9c4
/soc/oplus,pps_charge/silicon_p_770/oplus,curr_max_ma 0x1676
